name: Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: postgres
        PGHOST: postgres
        secret: GH
        PORT: 3000
    - run: npm run coverage
      env:
        POSTGRES_HOST: postgres
        POSTGRES_PORT: 5432
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: postgres
        PGHOST: postgres
        secret: GH
        PORT: 3000
